### PR TITLE
AOT support

### PR DESCRIPTION
**Pull request by Chocobozzz**

### CODE REVIEW

**Comment by FabianMeul** [comment]
@vinaygopinath Would love to see this merged, as your module currently breaks using the latest version of Angular-cli (due to lack of AOT support).

**Comment by bjornharvold** [comment]
+1

**Review by elephant — APPROVED** [review]

**Comment by FabianMeul** [comment]
So... it's approved. Who's in charge of merging this and pushing it to NPM? 🥇 @vinaygopinath

**Comment by DBuit** [comment]
@Chocobozzz or @FabianMeul Is it possible to use this because i cant wait for the merge i need to go live with my project :)

Hope to hear from one of you.
Thank you!

**Comment by Chocobozzz** [comment]
@DBuit You can try my build branch, it is what I use on my projet (https://github.com/Chocobozzz/PeerTube/blob/develop/client/package.json#L58).

**Comment by FabianMeul** [comment]
@DBuit Well, what I've done so far as a temporary solution is set a dependency to the repo of @Chocobozzz .

`"ng2-meta": "https://github.com/Chocobozzz/ng2-meta.git#master",`

The problem there is that the `dist` folder of this package is only created when it's being published to NPM, so we need to generate that manually using the following command. I'm assuming that you're on the root of your project:

`cd node_modules/ng2-meta && npm run ngc`

I've implemented the above in my Bamboo CI build.


EDIT: Using the build branch from @Chocobozzz makes a lot more sense :-D

**Comment by DBuit** [comment]
@FabianMeul i added ng2-meta to the packages as you said and run the ngc command on the packages but getting the follow 2 errors:

Error at /Users/daanbuit/vagrant7/www/website/node_modules/ng2-meta/src/meta.service.ts:17:8: Property 'filter' does not exist on type 'Observable<Event>'.
Error at /Users/daanbuit/vagrant7/www/website/node_modules/ng2-meta/src/meta.service.ts:17:15: Parameter 'event' implicitly has an 'any' type.

**Comment by DBuit** [comment]
@FabianMeul didnt see @Chocobozzz reaction gonna try that first :) thanks

**Comment by DBuit** [comment]
@Chocobozzz im using import {MetaService} from "ng2-meta"; in mij components to use the metaservice. it cant resolve the path anymore after using your build branch in my packages.json, any idea how to fix this?

this is what i got in my node_modules, im missing the dist folder

screen shot 2017-01-20 at 16 53 58

**Comment by DBuit** [comment]
@Chocobozzz i added the dist folder myself and i do not get any errors while compiling. But when it is running im getting: "No provider for MetaService"

**Comment by Chocobozzz** [comment]
@DBuit you need to add it to your root module: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/app.module.ts#L47

**Comment by DBuit** [comment]
@Chocobozzz if i do that im getting the follow error:
` Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule`

**Comment by FabianMeul** [comment]
are you sure you deleted your original ng2-meta module in your node_modules before reinstalling using npm? Because the above error is what this PR is solving ;-)

**Comment by FabianMeul** [comment]
I'm starting to think this project is abandoned...? 👎

**Comment by bjornharvold** [comment]
Maybe fork this repo plus your fix and let us all enjoy it?

**Comment by FabianMeul** [comment]
@Chocobozzz has this on a fork. :-)

I'm still hoping the maintainer will come back and merge + publish this...

**Comment by FabianMeul** [comment]
@elephant Any chance this gets merged...?

**Comment by Geoide** [comment]
This package https://github.com/nglibs/meta works for me and the changes are minimal.

**Comment by szykov** [comment]
@Geoide <del>this one doesn't work with lazy loading. </del>
well, okay I also switched to @nglibs/meta and it works just fine. It mimics a functionality of this one but not fully. Lazy loading works just fine.

**Comment by balazsnemeth** [comment]
@vinaygopinath, can you please merge this?

**Comment by Chocobozzz** [comment]
I personally moved to https://github.com/nglibs/meta too. Works well.

**Comment by gemal** [comment]
Can this get please get merged?

**Pull request closed without merging**
