### PR TITLE
Correctly set og:title and og:description using property i.s.o. name

### PR DESCRIPTION
**Pull request by henetiriki**
Fixed issue where Facebook tags were being set via `<meta name="" ... />` i.s.o. `<meta property="" ... />`

Added ability to add a `canonical` as well as on or more `alternate` link tags.

Automatically set Twitter and Facebook tags based on `title` and `description` tags.

### CODE REVIEW

**Comment by reneszabo** [comment]
Nice ! +1

**Comment by ds-manish** [comment]
I am looking the solution for this issue
`<meta name=""/>` i.s.o. `<meta property="" ... />`

**Comment by markoddi** [comment]
Hi,

How do I make the canonical tag change. I've got the title, description and keywords changing ok.

Do I simply do this:

```
 {
    path: 'home',
    component: HomeComponent,
    data: {
      meta: {
        title: 'Home page',
        description: 'Description of the home page', 
        canonical: 'mywebsite.com/home' 
      }
    }
  }
```

**Comment by henetiriki** [comment]
No, you have to add it in a separate `link` property. Have a look at the updated README in the [PR here.](https://github.com/ouq77/ng2-meta/blob/34044e07886d6f59ae67fbb393a4b35c3d48c2e5/README.MD)

**Pull request closed without merging**
